# Generated by Django 3.2.8 on 2021-11-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sajili',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
