# Generated by Django 3.2.8 on 2021-11-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0002_alter_sajili_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TumaPesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_mtumaji', models.CharField(max_length=13)),
                ('no_mpokeaji', models.CharField(max_length=13)),
                ('kiasi', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('tofauti', models.IntegerField()),
                ('jumla', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tuma Pesa',
                'verbose_name_plural': 'Tuma Pesa',
            },
        ),
        migrations.AlterModelOptions(
            name='sajili',
            options={'verbose_name': 'Sajili', 'verbose_name_plural': 'Sajili'},
        ),
    ]
