# Generated by Django 3.2.8 on 2021-11-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0004_alter_tumapesa_tofauti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kiwango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('maximum', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('tofauti', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kiwango',
                'verbose_name_plural': 'Viwango',
            },
        ),
        migrations.AlterField(
            model_name='sajili',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
