# Generated by Django 3.2.8 on 2021-11-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0005_auto_20211107_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiwango',
            name='fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='kiwango',
            name='maximum',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='kiwango',
            name='minimum',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='kiwango',
            name='tofauti',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=19),
        ),
    ]
